package com.mx.banorte.services.helloserviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-08-23T10:47:27.051-04:00
 * Generated source version: 3.5.5
 *
 */
@WebServiceClient(name = "HelloService",
                  wsdlLocation = "file:/C:/Users/geral/OneDrive/Escritorio/Git Lab WorkSpace/Arquetipos/svr02-bussines-gateway/src/main/resources/wsdl/contrato.wsdl",
                  targetNamespace = "http://HelloServiceImpl/")
public class HelloService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://HelloServiceImpl/", "HelloService");
    public final static QName HelloServicePort = new QName("http://HelloServiceImpl/", "HelloServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/geral/OneDrive/Escritorio/Git Lab WorkSpace/Arquetipos/svr02-bussines-gateway/src/main/resources/wsdl/contrato.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/geral/OneDrive/Escritorio/Git Lab WorkSpace/Arquetipos/svr02-bussines-gateway/src/main/resources/wsdl/contrato.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public HelloService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns HelloService
     */
    @WebEndpoint(name = "HelloServicePort")
    public com.mx.banorte.services.namespace.unknown.HelloService getHelloServicePort() {
        return super.getPort(HelloServicePort, com.mx.banorte.services.namespace.unknown.HelloService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloService
     */
    @WebEndpoint(name = "HelloServicePort")
    public com.mx.banorte.services.namespace.unknown.HelloService getHelloServicePort(WebServiceFeature... features) {
        return super.getPort(HelloServicePort, com.mx.banorte.services.namespace.unknown.HelloService.class, features);
    }

}
